### ISSUE TITLE
OIDC Conformance Test: Logout State issue

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#96] opened 2021-02-02 14:13 UTC
URL:

```
https://duendesoftware-test.azurewebsites.net/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjFBMTYzRTQzQzI0QUFEQUIyQzM2Q0JGNzMyNzM3ODQxIiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2R1ZW5kZXNvZnR3YXJlLXRlc3QuYXp1cmV3ZWJzaXRlcy5uZXQiLCJuYmYiOjE2MTIyNzUwMzksImlhdCI6MTYxMjI3NTAzOSwiZXhwIjoxNjEyMjc1MzM5LCJhdWQiOiJiYXNpYyIsImFtciI6WyJwd2QiXSwibm9uY2UiOiJRT2JxeWxON3ZRIiwiYXRfaGFzaCI6ImFwNTU3WXI4Rm4wMTlfRFBjNDFqaWciLCJzaWQiOiJDNzIxQTkxQzgxODYxMzU4OTFFNzc4MEM3OEY5QzVDNCIsInN1YiI6Ijg4NDIxMTEzIiwiYXV0aF90aW1lIjoxNjEyMjc1MDM4LCJpZHAiOiJsb2NhbCJ9.u93oVNLSzCR7tRj5kMdnuGUkQ4ckkAXwSlkxcdYyLFlKiqlnqFaEaUG85Bn06HqSLClcL92P7lbwvTzsBa7LEY9APjVdzlbgzqVbi7wmCwGG_G_eEf-3yM1JqtWE_h60S3_-eKtesubPdBfrLsKGMp70-FWBb5wcCUqb8XNhGHrmcojNuJqy-D4VO7OQO2CtcWZjHx3gvSyeP4MsHF87td0zE-DCW8NdoNHXGQOkzgkuRYERoSOCGadO2nLudvrScnmlKxm4iVqyvvogbnTj5FFct9kXYvWbl_dkwIwihEKr8Ykg5R2sKF6F6Fg6_451b_khedVIEZAxGUz7Vu2PoA&post_logout_redirect_uri=https://www.certification.openid.net/test/a/duende_oidc/post_logout_redirect&state=iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060'~/@~,,%23%3E%22%3D,-%3D%7C_%3E%3D%5C%26%5E.%7B~%5D);,;?
```

```
actual
iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060'~/@~,,#>"=,-=|_>=\&^.{~])
expected
iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060'~/@~,,#>"=,-=|_>=\&^.{~]);,;?
```

or

```
actual
OZCbBvUDAHfKgqBkMmpqWxaQlNKfutbyGEpSnoefWtPItvOUwS8539424422':~%.
expected
OZCbBvUDAHfKgqBkMmpqWxaQlNKfutbyGEpSnoefWtPItvOUwS8539424422':~%.;~.*]'$^,"`>~*`^^;$=</^&#
```

**Comment by brockallen** [comment] 2021-02-02 19:22
I think the issue is that we take the state param internally and encode it (using the default URL encoder) and it converts many of those values into encoded values. For example:

```
iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060'~/@~,,#>"=,-=|_>=\&^.{~]);,;?
```

becomes:
```
iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060%27~%2F@~,,%23%3E%22%3D,-%3D%7C_%3E%3D%5C%26%5E.%7B~%5D);,;%3F
```

Then when we redirect back to the test client, it's possibly not reading encoded values correctly. We'd need to confirm by watching the traffic in your browser during the test.

**Comment by brockallen** [comment] 2021-02-02 19:27
From the URL RFC:

```
An HTTP URL takes the form:

      http://<host>:<port>/<path>?<searchpart>

   where <host> and <port> are as described in Section 3.1. If :<port>
   is omitted, the port defaults to 80.  No user name or password is
   allowed.  <path> is an HTTP selector, and <searchpart> is a query
   string. The <path> is optional, as is the <searchpart> and its
   preceding "?". If neither <path> nor <searchpart> is present, the "/"
   may also be omitted.

   Within the <path> and <searchpart> components, "/", ";", "?" are
   reserved.  The "/" character may be used within HTTP to designate a
   hierarchical structure.


```
Thus, only alphanumerics, the special characters "$-_.+!*'(),", and
   reserved characters used for their reserved purposes may be used
   unencoded within a URL.
```

**Comment by brockallen** [comment] 2021-02-02 19:32
Furthermore, when we redirect the user back to:

```
https://localhost:44300/index.html?state=iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060%27~%2F@~,,%23%3E%22%3D,-%3D%7C_%3E%3D%5C%26%5E.%7B~%5D);,;%3F
```

then this URL is properly read with the state param as:

```
iOaurmcsIxbEylCxbSNbuoXttGmiFGKvsprSEGbteHcgKDBlfX4031238060'~/@~,,#>"=,-=|_>=\&^.{~]);,;?
```

According to this tool: https://codeamaze.com/web-utility/url-parser

**Comment by brockallen** [comment] 2021-03-03 14:22
Closing as not a bug.

**Closed by brockallen** 2021-03-03 14:22 UTC
Labels: bug report, wontfix
