### ISSUE TITLE
Seeing IdentityServer request slowness after upgrading from v5.2.3 to v6

### ISSUE THREAD

**Issue by billpieper** [DuendeSoftware/IdentityServer#694] opened 2022-01-27 15:35 UTC
We upgraded IdentityServer versions and made no other infrastructure changes, but we are seeing much slower response times post upgrade.  

We are using a SQL Azure database for the IdentityServer data store and Azure Kubernetes Service (AKS) to host IdentityServer via container.

Response time data from Application Insights when using IdentityServer v5.2.3:
![image](https://user-images.githubusercontent.com/682286/151389824-46433727-76cc-4162-9da0-b62338b9a6ff.png)

Similar view after updating to IdentityServer v6:
![image](https://user-images.githubusercontent.com/682286/151389897-08b95c93-401d-451d-83b1-d8323b9f4fd5.png)

In Issue #668 it was asked in caching was being used.  We had NOT implemented a cache up to this point. -- Yesterday, I enabled the in memory cache  (via service.AddIdentityServer().AddInMemoryCaching() per https://docs.duendesoftware.com/identityserver/v6/data/configuration/#caching-configuration-data)

Enabling in memory cache has helped a bit -- but the performance is still quite a bit slower than what we were seeing with v5.2.3:
![image](https://user-images.githubusercontent.com/682286/151390847-ca66b641-68a1-42ac-9d09-f07e354dfc2e.png)

**Comment by brockallen** [comment] 2022-01-27 15:42
Hi @billpieper -- What do you use for your user auth library/database (e.g. ASP.NET Identity)? I'd like to see a comparison of something that uses your user auth library (like the login page) of before and after outside of an OIDC workflow. In other words, how does that compare without any IdentityServer code running.

**Comment by billpieper** [comment] 2022-01-27 15:59
In our UI (vue js spa application) we are currently using oidc-client v1.9.1.
For users/database -- we federate with Azure AD and all our user identities originate there.

**Comment by hugoqribeiro** [comment] 2022-01-27 16:01
I've seen the same yesterday in our staging environment with the configuration store cache disabled (because of the other error) in the connect/authorize endpoint.
I could get to a point in Azure Application Insights where it seemed that there was some kind of contention around the queries that load the client and validate the resources configuration.
I wasn't able yet to look into the Azure SQL logs because that depends on our infra team.
Yeah... DevOps is still a pain... :)

**Comment by brockallen** [comment] 2022-01-27 16:19
Finally, what DB are you using for the stores @billpieper? SqlServer? Postgres? Or maybe you're not and it's all just in-memory?

**Comment by billpieper** [comment] 2022-01-27 16:56
I just updated my app to roll back the NuGet references for IdentityServer from 6.0.3 back to 5.2.4.  With only having made that change -- we are now seeing response times like what we had been seeing originally.  I left the app as .NET 6 and left all other references alone.

**Comment by brockallen** [comment] 2022-01-27 23:20
Just a quick update: we've been trying to recreate the conditions you're describing. Nothing really more to report at this time.

**Comment by hugoqribeiro** [comment] 2022-01-28 10:01
I'm disabling the store cache and enabling Azure SQL logs on our environment to see if we can find something useful.

**Comment by hugoqribeiro** [comment] 2022-01-28 16:16
There is really something going on with the authorize endpoint.

The cache is disabled and we're seeing some really slow requests.

Notice the timestamp on this one:

[Insights capture](https://www.dropbox.com/s/vkg9hwilbuhv3eu/Capture.png?dl=0)

The log for Duende.* was set to warning, so I don't have log there. I've changed it. Will have to wait for this to happen again.

**Comment by hugoqribeiro** [comment] 2022-01-28 17:02
> We're happy to help, but it's still not clear where exactly the issue is. I was trying to isolate where we thought the slowness came from. Is there any further diagnostics than can be gleaned from your environment? Maybe which DB queries are slow (and before vs after)?
> 
> If we think the client store query is the main culprit, then it would be interesting for someone to override it and do it in the style from 5.x: https://github.com/DuendeSoftware/IdentityServer/blob/5.2.4/src/EntityFramework.Storage/Stores/ClientStore.cs#L53-L70.
> 
> And the reason I think it's more likely it's the client store is that 1) it changed in 6.0 and 2) the .well-known endpoint loads all of the resource store, the comparison is about the same in the before/after, and it did not change in 6.0.

Confirmed that our problem is the client query.

```
SELECT [c].[Id], [c].[AbsoluteRefreshTokenLifetime], [c].[AccessTokenLifetime], [c].[AccessTokenType], [c].[AllowAccessTokensViaBrowser], [c].[AllowOfflineAccess], [c].[AllowPlainTextPkce], [c].[AllowRememberConsent], [c].[AllowedIdentityTokenSigningAlgorithms], [c].[AlwaysIncludeUserClaimsInIdToken], [c].[AlwaysSendClientClaims], [c].[AuthorizationCodeLifetime], [c].[BackChannelLogoutSessionRequired], [c].[BackChannelLogoutUri], [c].[CibaLifetime], [c].[ClientClaimsPrefix], [c].[ClientId], [c].[ClientName], [c].[ClientUri], [c].[ConsentLifetime], [c].[Created], [c].[Description], [c].[DeviceCodeLifetime], [c].[EnableLocalLogin], [c].[Enabled], [c].[FrontChannelLogoutSessionRequired], [c].[FrontChannelLogoutUri], [c].[IdentityTokenLifetime], [c].[IncludeJwtId], [c].[LastAccessed], [c].[LogoUri], [c].[NonEditable], [c].[PairWiseSubjectSalt], [c].[PollingInterval], [c].[ProtocolType], [c].[RefreshTokenExpiration], [c].[RefreshTokenUsage], [c].[RequireClientSecret], [c].[RequireConsent], [c].[RequirePkce], [c].[RequireRequestObject], [c].[SlidingRefreshTokenLifetime], [c].[UpdateAccessTokenClaimsOnRefresh], [c].[Updated], [c].[UserCodeType], [c].[UserSsoLifetime], [c0].[Id], [c0].[ClientId], [c0].[Origin], [c1].[Id], [c1].[ClientId], [c1].[GrantType], [c2].[Id], [c2].[ClientId], [c2].[Scope], [c3].[Id], [c3].[ClientId], [c3].[Type], [c3].[Value], [c4].[Id], [c4].[ClientId], [c4].[Created], [c4].[Description], [c4].[Expiration], [c4].[Type], [c4].[Value], [c5].[Id], [c5].[ClientId], [c5].[Provider], [c6].[Id], [c6].[ClientId], [c6].[PostLogoutRedirectUri], [c7].[Id], [c7].[ClientId], [c7].[Key], [c7].[Value], [c8].[Id], [c8].[ClientId], [c8].[RedirectUri]
FROM [IDSv4].[Clients] AS [c]
LEFT JOIN [IDSv4].[ClientCorsOrigins] AS [c0] ON [c].[Id] = [c0].[ClientId]
LEFT JOIN [IDSv4].[ClientGrantTypes] AS [c1] ON [c].[Id] = [c1].[ClientId]
LEFT JOIN [IDSv4].[ClientScopes] AS [c2] ON [c].[Id] = [c2].[ClientId]
LEFT JOIN [IDSv4].[ClientClaims] AS [c3] ON [c].[Id] = [c3].[ClientId]
LEFT JOIN [IDSv4].[ClientSecrets] AS [c4] ON [c].[Id] = [c4].[ClientId]
LEFT JOIN [IDSv4].[ClientIdPRestrictions] AS [c5] ON [c].[Id] = [c5].[ClientId]
LEFT JOIN [IDSv4].[ClientPostLogoutRedirectUris] AS [c6] ON [c].[Id] = [c6].[ClientId]
LEFT JOIN [IDSv4].[ClientProperties] AS [c7] ON [c].[Id] = [c7].[ClientId]
LEFT JOIN [IDSv4].[ClientRedirectUris] AS [c8] ON [c].[Id] = [c8].[ClientId]
WHERE [c].[ClientId] = 'elevationfrw-implict'
ORDER BY [c].[Id], [c0].[Id], [c1].[Id], [c2].[Id], [c3].[Id], [c4].[Id], [c5].[Id], [c6].[Id], [c7].[Id]
```

This produces, for this specific client, nothing less than 255 990 rows!!!
Because of CorsOrigins, RedirectUris, and PostLogoutRedirectUris. Each of these has 30 to 50 records.

Should I override the client store or do you think it should be done in the source?

**Comment by brockallen** [comment] 2022-01-28 17:58
> Confirmed that our problem is the client query.

That's good info. My main concern is that once caching is enabled, then the difference should go away. So something else is an issue, I think.

Also, in our testing so far -- we are doing local tests, and then tests in azure on both v5 and v6. All of our local tests between v5 and v6 don't seem to show any difference. But once we push them to azure, we do see a difference between v5 and v6, where v6 seems to be somewhat slower. The discrepancy between the two environments don't help... 

We're also testing different configurations -- with and without a database. 

Anyway, we're still spending time looking into it trying to understand really what's going on.

**Comment by brockallen** [comment] 2022-01-28 18:00
> Should I override the client store or do you think it should be done in the source?

For the time being, sure. And if after all of this we really think this new query style done in v6 is causing problems, I have no issue rolling it back to how it was in v5 (despite the guidance we got from the EF team).

@billpieper Can you try the same what @hugoqribeiro has done and see if that affects your data?

**Comment by hugoqribeiro** [comment] 2022-01-28 19:26
> My main concern is that once caching is enabled, then the difference should go away.

It's better but not too much. If you think that the cache expiration is absolute 5 minutes.
Every 5 mins, any user will wait 30+ seconds to start the application...

Also worth noting, his construct isn't really friendly to replace `ClientStore`:

```
public static IIdentityServerBuilder AddClientStore<T>(this IIdentityServerBuilder builder)
    where T : class, IClientStore
{
    builder.Services.TryAddTransient(typeof(T));
    builder.Services.AddTransient<IClientStore, ValidatingClientStore<T>>();
    return builder;
}
```

**Comment by brockallen** [comment] 2022-01-31 14:34
@billpieper Can you let us know your exact Azure specs for the service plan and the DB?

**Comment by billpieper** [comment] 2022-01-31 15:50
We deploy as containers in AKS (Azure Kubernetes Service).  AKS nodepool is Linux (node size = Standard_D2s_v4).  Node CPU and memory utilization is pretty low and the pods running identity server don't seem to be memory or cpu constrained.

**Comment by brockallen** [comment] 2022-02-01 18:57
Update for you both. We spent several days doing profiling both v5 and v6. We have confirmed the query per issue with the client store, and that code change is the only significant change that was made from v5 to v6. Given this, we plan to revert the store back to its v5 behavior, and we'll do a release. Hopefully this addresses the issues you see in your environment.

**Comment by brockallen** [comment] 2022-02-02 17:15
This PR was merged. Thanks all!

**Closed as completed by brockallen** 2022-02-02 17:15 UTC

**Comment by brockallen** [comment] 2022-02-02 17:40
version 6.0.4 has been released to NuGet
