### ISSUE TITLE
Back channel logout token might incorrectly contain `logout_token` as `iss`

### ISSUE THREAD

**Issue by AndersAbel** [DuendeSoftware/IdentityServer#1481] opened 2023-12-04 12:33 UTC
If the request does not contain an issuer, the issuer name service should be invoked to get the issuer. This is done automatically in the two param version of IIdentityServerTools.IssueJwtAsync.

https://github.com/DuendeSoftware/IdentityServer/pull/1170 adds support for setting `typ` to `logout+jwt`. Unfortunately the code path with no issuer in the request now mistakenly uses the three param version of the constructor. This results in the token type `logout_token` being used as `iss`

**Comment by josephdecock** [comment] 2023-12-12 21:38
@AndersAbel Is there a good way to reproduce this issue in a test? The bug makes sense at the level of the code path within IdentityServerTools, but I don't see how we would invoke that through "normal" operations. The only way I can think of making this happen is, invoke the session management service from the UI, and don't pass the session identifier into the context object that you need to pass to the service.

**Comment by josephdecock** [comment] 2023-12-13 20:37
I pulled this forward from 6.3.6 to a new 6.3.7 milestone (since 6.3.6 is already released). Unfortunately the fix will require a breaking change, so should we push it to v7?

**Comment by AndersAbel** [comment] 2023-12-13 21:25
This is customer reported. They had to rollback to a previous version because of this. We need to coordinate with them if they can wait until v7.

**Comment by brockallen** [comment] 2023-12-15 13:49
PR merged.

**Closed by brockallen** 2023-12-15 13:49 UTC
Labels: bug

**Comment by josephdecock** [comment] 2023-12-17 17:03
For future reference, we merged because we found an approach that would not be as disruptive, and because this is a bug fix.
