### ISSUE TITLE
Consider OTel Metrics

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#1200] opened 2023-03-01 08:10 UTC
https://opentelemetry.io/docs/reference/specification/metrics/

**Comment by josephdecock** [comment] 2023-03-01 21:43
Is this a duplicate of #1199?

**Comment by leastprivilege** [comment] 2023-03-02 07:52
yes. thanks!

**Comment by leastprivilege** [comment] 2023-07-06 13:58
YouTube video: https://youtu.be/c4AJlZeX2fE

**Comment by leastprivilege** [comment] 2023-07-07 05:40
Recap:

* We pick a first round of useful metrics and define them in IdentityServer
* We discuss separate metrics vs metrics with tags/properties
* We emit the metrics from within the core engine
* Maybe we need to have metrics in the QS UI (e.g. login success/failure)

@AndersAbel sounds good?

**Comment by AndersAbel** [comment] 2023-07-11 20:37
@leastprivilege Yes, looks good. First step will be to create the list of useful metrics and discuss.

**Comment by mrjamiebowman** [comment] 2023-08-03 13:18
Just wanted to reach out and tell you guys that you're doing a wonderful job with this. 

Open Telemetry is the future, we have been experimenting with this and Identity Server 6 and it has made troubleshooting performance issues significantly easier. 

I saw the incoming pull request for adding Meters/Metric Counters around events like token creation, failures. That is amazing! We love that you all are doing this because we want to be able to create alerts and rules if those metrics drop below a threshold or go over. This is wonderful and I look forward to seeing this in IDS 7.

**Comment by AndersAbel** [comment] 2023-08-03 16:20
@mrjamiebowman Thank you for your kind words. If you have any suggestions for events that are important to consider for the first round of metrics, please feel free to share them here. Any other opinions on how to design the metrics setup based on your experience are useful too.

**Comment by AndersAbel** [comment] 2023-11-01 12:24
@mrjamiebowman There's now a pull request for the first set of counters/metrics. If you have any feedback, please feel free to leave a comment.

**Closed** 2023-11-03 13:43 UTC
Labels: feature idea
